"""Change Project column name to title

Revision ID: 421157f1fd2a
Revises: e328f45f3189
Create Date: 2022-09-23 13:51:06.906411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '421157f1fd2a'
down_revision = 'e328f45f3189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('title', sa.String(length=128), nullable=True))
    op.drop_column('project', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('name', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('project', 'title')
    # ### end Alembic commands ###
