"""Add fee column to Quarter

Revision ID: a488685e7a93
Revises: dc2763cd802d
Create Date: 2022-09-05 14:04:36.250342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a488685e7a93'
down_revision = 'dc2763cd802d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quarter', sa.Column('fee', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quarter', 'fee')
    # ### end Alembic commands ###
