"""Add AccountSnapshot table

Revision ID: a8996bfb34fc
Revises: f67eff5ddb42
Create Date: 2022-07-15 08:44:02.152129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8996bfb34fc'
down_revision = 'f67eff5ddb42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('market_value', sa.Float(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_snapshot_date'), 'account_snapshot', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_snapshot_date'), table_name='account_snapshot')
    op.drop_table('account_snapshot')
    # ### end Alembic commands ###
