"""Add FeeSchedule and FeeRule

Revision ID: dc2763cd802d
Revises: eb1a7c096a44
Create Date: 2022-09-02 18:00:03.246140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc2763cd802d'
down_revision = 'eb1a7c096a44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee_rule', sa.Column('flat', sa.Float(), nullable=True))
    op.add_column('fee_schedule', sa.Column('name', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_fee_schedule_name'), 'fee_schedule', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fee_schedule_name'), table_name='fee_schedule')
    op.drop_column('fee_schedule', 'name')
    op.drop_column('fee_rule', 'flat')
    # ### end Alembic commands ###
