"""Add Project and Task models

Revision ID: e328f45f3189
Revises: a488685e7a93
Create Date: 2022-09-22 14:11:04.530265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e328f45f3189'
down_revision = 'a488685e7a93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('create_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_create_date'), 'project', ['create_date'], unique=False)
    op.create_index(op.f('ix_project_due_date'), 'project', ['due_date'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('create_date', sa.Date(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_completed'), 'task', ['completed'], unique=False)
    op.create_index(op.f('ix_task_create_date'), 'task', ['create_date'], unique=False)
    op.create_index(op.f('ix_task_due_date'), 'task', ['due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_due_date'), table_name='task')
    op.drop_index(op.f('ix_task_create_date'), table_name='task')
    op.drop_index(op.f('ix_task_completed'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_project_due_date'), table_name='project')
    op.drop_index(op.f('ix_project_create_date'), table_name='project')
    op.drop_table('project')
    # ### end Alembic commands ###
